package net.codersdownunder.gemmod.common.recipes;

import java.util.function.Consumer;

import net.codersdownunder.gemmod.GemMod;
import net.codersdownunder.gemmod.common.recipes.builders.DippingRecipeBuilder;
import net.codersdownunder.gemmod.init.ItemInit;
import net.codersdownunder.gemmod.utils.GeomancyTags;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Items;

public class GeomancyDippingRecipeProvider extends RecipeProvider {
	
	public GeomancyDippingRecipeProvider(DataGenerator generatorIn) {
        super(generatorIn);
    }

	@Override
	protected void buildCraftingRecipes(Consumer<FinishedRecipe> consumer) {
		
		DippingRecipeBuilder.dipping(ItemInit.AGATE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.CYAN_DYE)
		.requires(Items.KELP)
		.requires(Items.GRAVEL)
		.requires(Items.PACKED_ICE)
		.requires(Items.SLIME_BALL)
		.requires(Items.PACKED_ICE)
		.requires(Items.GRAVEL)
		.requires(Items.KELP)
		.requires(Items.CYAN_DYE)
		.requires(Items.PRISMARINE)
		.requires(Items.SLIME_BALL)
		.requires(Items.PRISMARINE)
		.requires(Items.SLIME_BALL)
		.requires(Items.KELP)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.CHRYSOCOLLA.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.PACKED_ICE)
		.requires(Items.SNOWBALL)
		.requires(Items.DIORITE)
		.requires(Items.CLAY)
		.requires(Items.ICE)
		.requires(Items.CLAY)
		.requires(Items.DIORITE)
		.requires(Items.SNOWBALL)
		.requires(Items.PACKED_ICE)
		.requires(Items.PACKED_ICE)
		.requires(Items.ICE)
		.requires(Items.PACKED_ICE)
		.requires(Items.PACKED_ICE)
		.requires(Items.SNOWBALL)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.MALACHITE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(ItemTags.LEAVES)
		.requires(Items.SLIME_BALL)
		.requires(Items.ANDESITE)
		.requires(Items.WARPED_HYPHAE)
		.requires(Items.TWISTING_VINES)
		.requires(Items.WARPED_HYPHAE)
		.requires(Items.ANDESITE)
		.requires(Items.SLIME_BALL)
		.requires(ItemTags.LEAVES)
		.requires(Items.TWISTING_VINES)
		.requires(Items.TWISTING_VINES)
		.requires(Items.TWISTING_VINES)
		.requires(Items.WARPED_HYPHAE)
		.requires(Items.SLIME_BALL)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.JADE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.SLIME_BALL)
		.requires(Items.GREEN_DYE)
		.requires(Items.DIRT)
		.requires(ItemTags.SMALL_FLOWERS)
		.requires(Items.SUGAR_CANE)
		.requires(ItemTags.SMALL_FLOWERS)
		.requires(Items.DIRT)
		.requires(Items.GREEN_DYE)
		.requires(Items.SLIME_BALL)
		.requires(ItemTags.SMALL_FLOWERS)
		.requires(Items.SUGAR_CANE)
		.requires(ItemTags.SMALL_FLOWERS)
		.requires(Items.SUGAR_CANE)
		.requires(Items.GREEN_DYE)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.PERIDOT.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.HONEYCOMB)
		.requires(Items.SLIME_BALL)
		.requires(Items.GRANITE)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.GRANITE)
		.requires(Items.SLIME_BALL)
		.requires(Items.HONEYCOMB)
		.requires(Items.GRANITE)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.GRANITE)
		.requires(Items.HONEYCOMB)
		.requires(Items.SLIME_BALL)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.TOPAZ.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.REDSTONE)
		.requires(Items.YELLOW_DYE)
		.requires(Items.BASALT)
		.requires(Items.BAMBOO)
		.requires(Items.BAMBOO)
		.requires(Items.BAMBOO)
		.requires(Items.BASALT)
		.requires(Items.YELLOW_DYE)
		.requires(Items.REDSTONE)
		.requires(Items.BASALT)
		.requires(Items.BAMBOO)
		.requires(Items.BASALT)
		.requires(Items.REDSTONE)
		.requires(Items.YELLOW_DYE)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.CITRINE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.RED_SAND)
		.requires(Items.GLASS)
		.requires(Items.ANDESITE)
		.requires(Items.PURPUR_BLOCK)
		.requires(Items.SEA_LANTERN)
		.requires(Items.PURPUR_BLOCK)
		.requires(Items.ANDESITE)
		.requires(Items.GLASS)
		.requires(Items.RED_SAND)
		.requires(Items.GRAVEL)
		.requires(Items.SEA_LANTERN)
		.requires(Items.GRAVEL)
		.requires(Items.RED_SAND)
		.requires(Items.GLASS)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.JASPER.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.BASALT)
		.requires(Items.ORANGE_DYE)
		.requires(Items.MAGMA_BLOCK)
		.requires(Items.REDSTONE)
		.requires(Items.REDSTONE)
		.requires(Items.GLOWSTONE_DUST)
		.requires(Items.MAGMA_BLOCK)
		.requires(Items.BASALT)
		.requires(Items.BASALT)
		.requires(Items.RED_SAND)
		.requires(Items.GLOWSTONE_DUST)
		.requires(Items.RED_SAND)
		.requires(Items.CAMPFIRE)
		.requires(Items.RED_DYE)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.RUBY.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.SUGAR)
		.requires(Items.FLINT)
		.requires(Items.BLACKSTONE)
		.requires(Items.CHARCOAL)
		.requires(Items.REDSTONE)
		.requires(Items.CHARCOAL)
		.requires(Items.BLACKSTONE)
		.requires(Items.FLINT)
		.requires(Items.SUGAR)
		.requires(Items.SUGAR)
		.requires(Items.REDSTONE)
		.requires(Items.SUGAR)
		.requires(Items.OBSIDIAN)
		.requires(Items.FLINT)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.GARNET.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.SOUL_SAND)
		.requires(Items.REDSTONE)
		.requires(Items.POPPY)
		.requires(Items.SOUL_SOIL)
		.requires(Items.BLACKSTONE)
		.requires(Items.SOUL_SOIL)
		.requires(Items.POPPY)
		.requires(Items.BLACKSTONE)
		.requires(Items.SOUL_SAND)
		.requires(Items.CRIMSON_HYPHAE)
		.requires(Items.BLACKSTONE)
		.requires(Items.CRIMSON_HYPHAE)
		.requires(Items.CRIMSON_HYPHAE)
		.requires(Items.REDSTONE)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.SPINEL.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.BEETROOT)
		.requires(Items.APPLE)
		.requires(Items.GRANITE)
		.requires(Items.PINK_TULIP)
		.requires(Items.PINK_DYE)
		.requires(Items.PINK_TULIP)
		.requires(Items.GRANITE)
		.requires(Items.APPLE)
		.requires(Items.BEETROOT)
		.requires(Items.DIRT)
		.requires(Items.PINK_DYE)
		.requires(Items.DIRT)
		.requires(Items.SOUL_CAMPFIRE)
		.requires(Items.APPLE)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.AMETHYST.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.SOUL_SAND)
		.requires(Items.STRIPPED_CRIMSON_HYPHAE)
		.requires(Items.JACK_O_LANTERN)
		.requires(Items.SOUL_TORCH)
		.requires(Items.PURPLE_DYE)
		.requires(Items.SOUL_TORCH)
		.requires(Items.JACK_O_LANTERN)
		.requires(Items.STRIPPED_CRIMSON_HYPHAE)
		.requires(Items.SOUL_SAND)
		.requires(Items.PURPLE_STAINED_GLASS)
		.requires(Items.PURPLE_DYE)
		.requires(Items.PURPLE_STAINED_GLASS)
		.requires(Items.SOUL_SAND)
		.requires(Items.STRIPPED_CRIMSON_HYPHAE)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.CHAROITE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.CHARCOAL)
		.requires(Items.PURPLE_DYE)
		.requires(Items.DIRT)
		.requires(Items.WARPED_STEM)
		.requires(Items.BONE_MEAL)
		.requires(Items.CRIMSON_STEM)
		.requires(Items.DIRT)
		.requires(Items.PURPLE_DYE)
		.requires(Items.CHARCOAL)
		.requires(Items.DIRT)
		.requires(Items.BONE_MEAL)
		.requires(Items.DIRT)
		.requires(Items.ROTTEN_FLESH)
		.requires(Items.PURPLE_DYE)
		.group(GemMod.MODID)
		.save(consumer);

		DippingRecipeBuilder.dipping(ItemInit.SAPPHIRE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.DARK_OAK_LOG)
		.requires(Items.OBSIDIAN)
		.requires(Items.DEEPSLATE)
		.requires(Items.DARK_OAK_LOG)
		.requires(Items.DEEPSLATE)
		.requires(Items.OBSIDIAN)
		.requires(Items.DARK_OAK_LOG)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.DARK_OAK_LOG)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.OBSIDIAN)
		.requires(Items.DARK_OAK_LOG)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.ONYX.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.STONE)
		.requires(Items.BLACKSTONE)
		.requires(Items.DEEPSLATE)
		.requires(Items.ANDESITE)
		.requires(Items.GRAVEL)
		.requires(Items.ANDESITE)
		.requires(Items.DEEPSLATE)
		.requires(Items.BLACKSTONE)
		.requires(Items.STONE)
		.requires(Items.COAL)
		.requires(Items.GRAVEL)
		.requires(Items.COAL)
		.requires(Items.DEEPSLATE)
		.requires(Items.BLACKSTONE)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.SPHENE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.DIRT)
		.requires(Items.SUGAR)
		.requires(Items.SAND)
		.requires(Items.GLOWSTONE_DUST)
		.requires(Items.ORANGE_DYE)
		.requires(Items.GLOWSTONE_DUST)
		.requires(Items.SAND)
		.requires(Items.GOLD_NUGGET)
		.requires(Items.DIRT)
		.requires(Items.GLOWSTONE)
		.requires(Items.ORANGE_DYE)
		.requires(Items.GLOWSTONE)
		.requires(Items.GLOWSTONE_DUST)
		.requires(Items.SUGAR)
		.group(GemMod.MODID)
		.save(consumer);
		
		DippingRecipeBuilder.dipping(ItemInit.RHODONITE.get(), 1000)
		.requires(GeomancyTags.Items.QUARTZ)
		.requires(Items.BLACKSTONE)
		.requires(Items.LAPIS_LAZULI)
		.requires(Items.END_STONE)
		.requires(Items.BLACKSTONE)
		.requires(Items.CHARCOAL)
		.requires(Items.BLACKSTONE)
		.requires(Items.END_STONE)
		.requires(Items.ENDER_PEARL)
		.requires(Items.BLACKSTONE)
		.requires(Items.END_STONE)
		.requires(Items.CHARCOAL)
		.requires(Items.END_STONE)
		.requires(Items.BLACK_DYE)
		.requires(Items.LAPIS_LAZULI)
		.group(GemMod.MODID)
		.save(consumer);
		
		// Add more below
		
	}
}