modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/codersdownunder"
license="LGPL V3"

[[mods]]
    modId="geomancyadditions"
    version="${file.jarVersion}"
    displayName="Geomancy: Additions"
    displayURL=""
    authors="Trhod177, Lena_Cupid"
    credits=""
    logoFile="logo.png"
    description='''Geomancy Additions'''

[[dependencies.geomancyadditions]]
    modId="geomancy"
    mandatory=true
    versionRange="[${version}]"
    side="BOTH"
    
[modproperties.geomancyadditions]
    catalogueItemIcon="geomancyadditions:purpur_wall" #Optional support for Cataloque mod.
    configuredBackground="geomancy:textures/blocks/chasm_planks.png" #Optional support for Configured mod.